#!/bin/bash
#SBATCH --job-name=yayayaya             # Job name
#SBATCH --output=output.%A.txt   # Standard output and error log
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --mem=40G                   # Total RAM to be used
#SBATCH --cpus-per-task=8          # Number of CPU cores
#SBATCH --gres=gpu:1                # Number of GPUs (per node)
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH --qos=gpu-8                 # To enable the use of up to 8 GPUs

hostname
if [ -f "/tmp/yahia.dalbah/CARRADA/Carrada/data_seq_ref.json" ]
then
    echo "Directory exists"
    cd /home/yahia.dalbah/carrada/mvrss/utils/
    python set_paths.py --carrada /tmp/yahia.dalbah/CARRADA/ --logs /home/yahia.dalbah/carrada/mvrss/carrada_logs
else
    mkdir /tmp/yahia.dalbah
    cd /tmp/yahia.dalbah
    mkdir /tmp/yahia.dalbah/CARRADA
    cp /l/users/yahia.dalbah/Carrada.tar.gz /tmp/yahia.dalbah/CARRADA
    cd CARRADA
    tar -xvf Carrada.tar.gz

    cd /home/yahia.dalbah/carrada/mvrss/utils/
    python set_paths.py --carrada /tmp/yahia.dalbah/CARRADA/ --logs /home/yahia.dalbah/carrada/mvrss/carrada_logs
#python set_paths.py --carrada /l/users/yahia.dalbah/ --logs /home/yahia.dalbah/carrada/mvrss/carrada_logs
fi

# cd /home/yahia.dalbah/carrada/mvrss/utils/
# python set_paths.py --carrada /l/users/yahia.dalbah/ --logs /home/yahia.dalbah/carrada/mvrss/carrada_logs
cd /home/yahia.dalbah/TransRadar/mvrss/ 
python -u train.py --cfg config_files/TransRadar.json --cp_store /l/users/yahia.dalbah/carrada_logs_dummy

EOL
