#!/bin/bash
#SBATCH --job-name=yayayaya             # Job name
#SBATCH --output=output.%A.txt   # Standard output and error log
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --mem=40G                   # Total RAM to be used
#SBATCH --cpus-per-task=8          # Number of CPU cores
#SBATCH --gres=gpu:1                # Number of GPUs (per node)
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH --qos=gpu-8                 # To enable the use of up to 8 GPUs

hostname

cd /home/yahia.dalbah/TransRadar/mvrss/utils/
python set_paths.py --carrada /l/users/yahia.dalbah/ --logs /home/yahia.dalbah/TransRadar/mvrss/carrada_logs

cd /home/yahia.dalbah/TransRadar/mvrss/ 

python -u test.py --cfg /home/yahia.dalbah/TransRadar/mvrss/carrada_logs/carrada/TransRadar/TransRadar_0/config.json

EOL

